# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f944b2ce285d1cfcda9439763de369619be530218ef43a70d7f7d3f01aa4a1e3586e8cd1cadcfa5543624a76d65e76001f5ba9bf48ad2fad84cc9c855dde848

test:
  secret_key_base: 837c5ec8990fcd69a02309a29f7f436aa9efd02d7120469901087ba0d92d4ea89315e134998d793fbf2ee036b0df28c98fefd81ceaa9c6f2b709e549fc10ed39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
